networks:
  default:
  devbox_devnet:
    external: true

services:
  api:
    networks:
      - default
      - devbox_devnet
  worker:
    networks:
      - default
      - devbox_devnet
  redis:
    networks:
      - default
